dbt_project:
  outputs:
    dev:
      type: bigquery
      dataset: transformed_data
      method: service-account
      project: my-project-1-268308
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE_PATH', '') }}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      # Use an env variable to indicate your JSON key file path
      location: asia-east1
      priority: interactive
      # Indicate your BigQuery project ID
      threads: 1
  target: dev